-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-06-22T18:58:49.916Z
--<DBT_CODE>

WITH cleansed_listings AS (SELECT * FROM {{ ref('cleansed_listings') }})

select
*
from
cleansed_listings
limit
100
--</DBT_CODE>
--<ORIGINAL_CODE>
--select
--  *
--from
--  cleansed_listings
--limit
--  100
--</ORIGINAL_CODE>