-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-07-07T19:54:53.025Z
--<DBT_CODE>

WITH cleansed_listings AS (SELECT * FROM {{ ref('cleansed_listings') }})

select
host_id,
name,

from
cleansed_listings
--</DBT_CODE>
--<ORIGINAL_CODE>
--select
--  host_id,
--  name,
--
--from
--  cleansed_listings
--
--</ORIGINAL_CODE>