-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-07-06T19:57:51.703Z
--<DBT_CODE>

WITH cleansed_listings AS (SELECT * FROM {{ ref('cleansed_listings') }})

select
host_id,
name,

from
cleansed_listings
limit
1000
--</DBT_CODE>
--<ORIGINAL_CODE>
--select
--  host_id,
--  name,
--
--from
--  cleansed_listings
--limit
--  1000
--</ORIGINAL_CODE>