--<SQL_QUERY_COULD_NOT_BE_PARSED>
--UPDATED: 2025-07-03T12:45:48.973Z
--<ORIGINAL_CODE>
--with
--   price_cleaned as (
--     select
--       l.id as listing_id,
--       l.host_id,
--       cast(
--         regexp_replace(l.price, '[$,]', '') as decimal (10, 2)
--       ) as price
--     from
--       cleansed_listings l
--     where
--       try_cast(
--         regexp_replace(l.price, '[$,]', '') as decimal (10, 2)
--       ) is not null
--   ),
--   host_revenue as (
--     select
--       h.id as host_id,
--       h.name as host_name,
--       h.is_superhost,
--       sum(pc.price) as total_revenue,
--       count(pc.listing_id) as total_listings,
--       avg(pc.price) as average_listing_price,
--       max(pc.price) as highest_price_listing,
--       min(pc.price) as lowest_price_listing,
--       max(l.updated_at) as last_updated_at
--     from
--       cleansed_hosts h
--       join price_cleaned pc on h.id = pc.host_id
--       join cleansed_listings l on l.host_id = h.id
--     where
--       h.name <> 'demo'
--       and h.id is not null
--     group by
--       h.id,
--       h.name,
--       h.is_superhost
--   )
--select
--   host_id,
--   host_name,
--   is_superhost,
--   total_revenue,
--   total_listings,
--   average_listing_price,
--   highest_price_listing,
--   lowest_price_listing,
--   last_updated_at
--from
--   host_revenue
--order by
--   total_revenue desc
--</ORIGINAL_CODE>