-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-08-25T13:17:46.364Z
--<DBT_CODE>

WITH RAW_LISTINGS__RAW_LISTINGS AS ( SELECT * FROM {{ source('RAW_LISTINGS', 'RAW_LISTINGS') }})

SELECT * FROM (
select
*
from
RAW_LISTINGS__RAW_LISTINGS
where
id is not null
limit 1000
) AS montara_model
--<INCREMENTAL>
{% if is_incremental() %}
  WHERE updated_at >= (SELECT max(updated_at) FROM {{ this }})
{% endif %}
--</INCREMENTAL>
--</DBT_CODE>
--<ORIGINAL_CODE>
--select
--  *
--from
--  RAW_LISTINGS__RAW_LISTINGS
--where
--  id is not null
--  limit 1000
--</ORIGINAL_CODE>