-- AUTO GENERATED BY MONTARA
--<DBT_CODE>

WITH RAW_LISTINGS__RAW_LISTINGS AS ( SELECT * FROM {{ source('RAW_LISTINGS', 'RAW_LISTINGS') }})

SELECT
host_id,   name,   room_type,   price,   listing_url,   minimum_nights,   created_at,   updated_at FROM
RAW_LISTINGS__RAW_LISTINGS
ORDER BY
created_at DESC
--</DBT_CODE>
--<ORIGINAL_CODE>
---- Select relevant columns from the raw listings table with specific filtering criteria
--SELECT
--  host_id, -- Host identifier
--  name, -- Name of the listing
--  room_type, -- Type of room
--  price, -- Price of the listing
--  listing_url, -- URL of the listing
--  minimum_nights, -- Minimum number of nights for booking
--  created_at, -- Creation timestamp
--  updated_at -- Update timestamp
--FROM 
--  RAW_LISTINGS__RAW_LISTINGS
--ORDER BY
--  created_at DESC -- Order by newest listings
--</ORIGINAL_CODE>