-- AUTO GENERATED BY MONTARA
--<DBT_CODE>

WITH RAW_LISTINGS__RAW_LISTINGS AS ( SELECT * FROM {{ source('RAW_LISTINGS', 'RAW_LISTINGS') }})

select
id as "actual list price: list price*quantity"
from
raw_listings__raw_listings
--</DBT_CODE>
--<ORIGINAL_CODE>
--select
--  id as "actual list price: list price*quantity"
--from
--  raw_listings__raw_listings
--</ORIGINAL_CODE>