
# AUTO GENERATED BY MONTARA
#<ORIGINAL_CODE>
'''
List sources and models in the function definition as below
def another_py(sourceA, modelA)  
'''
def another_py(stg_orders):
  return model
#</ORIGINAL_CODE>
def model(dbt, session):
    stg_orders = dbt.ref('stg_orders')
    result = another_py(stg_orders)
    
    return result
