-- AUTO GENERATED BY MONTARA
--<DBT_CODE>

WITH hosts_with_multiple_listings AS (SELECT * FROM {{ ref('hosts_with_multiple_listings') }})

select * from hosts_with_multiple_listings
--</DBT_CODE>
--<ORIGINAL_CODE>
--select * from hosts_with_multiple_listings 
--</ORIGINAL_CODE>