-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-06-05T06:24:11.926Z
--<DBT_CODE>

WITH cleansed_listings AS (SELECT * FROM {{ ref('cleansed_listings') }})

select * from cleansed_listings
--</DBT_CODE>
--<ORIGINAL_CODE>
--select * from cleansed_listings 
--</ORIGINAL_CODE>