-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-10-15T14:36:49.590Z
--<DBT_CODE>

WITH cleansed_hosts AS (SELECT * FROM {{ ref('cleansed_hosts') }})

select * from cleansed_hosts
--</DBT_CODE>
--<ORIGINAL_CODE>
--select * from cleansed_hosts
--</ORIGINAL_CODE>