-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-06-01T09:47:13.292Z
--<DBT_CODE>

    {{
      config(
        post_hook=["\n  \n  {% if target.name == 'prod' %}\n    {{log('Running retention policy for {{this}}. Staging retention days: N/A, Production retention days: 180.')}}\n    DELETE FROM {{this}} WHERE CREATED_AT < DATEADD(day, -180, CURRENT_DATE())\n  \n  {% endif %}\n  "],
      )
    }}
    
WITH 
cleansed_hosts AS (
  SELECT * FROM {{ ref('cleansed_hosts') }}
  {% if is_incremental() %}
    WHERE CREATED_AT > (
      (SELECT max(CREATED_AT) FROM {{ this }})
        - INTERVAL '0 DAY'
    )
  {% endif %}
)

select
current_date as current_date,
c.*
from
cleansed_hosts c
--</DBT_CODE>
--<ORIGINAL_CODE>
--select
--  current_date as current_date,
--  c.*
--from
--  cleansed_hosts c
--</ORIGINAL_CODE>