-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-09-29T11:32:23.581Z
--<DBT_CODE>

WITH orders AS (SELECT * FROM {{ ref('orders') }})
, 
cleansed_hosts AS (
  SELECT * FROM {{ ref('cleansed_hosts') }}
  {% if is_incremental() %}
    WHERE CREATED_AT > (
      (SELECT max(CREATED_AT) FROM {{ this }})
        - INTERVAL '0 DAY'
    )
  {% endif %}
)

select
c.*,
(select sum(o.AMOUNT) from orders o where o.CUSTOMER_ID = c.ID) as total_revenue,
current_date as current_date
from
cleansed_hosts c
limit 1000
--</DBT_CODE>
--<ORIGINAL_CODE>
--select
--  c.*,
--  (select sum(o.AMOUNT) from orders o where o.CUSTOMER_ID = c.ID) as total_revenue,
--  current_date as current_date
--from
--  cleansed_hosts c
--  limit 1000
--</ORIGINAL_CODE>