-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-06-01T09:32:17.010Z
--<DBT_CODE>

    {{
      config(
        post_hook=["\n  \n  {% if target.name == 'prod' %}\n    {{log('Running retention policy for {{this}}. Staging retention days: N/A, Production retention days: 180.')}}\n    DELETE FROM {{this}} WHERE CREATED_AT < DATEADD(day, -180, CURRENT_DATE())\n  \n  {% endif %}\n  "],
      )
    }}
    
WITH orders AS (SELECT * FROM {{ ref('orders') }})
, 
cleansed_hosts AS (
  SELECT * FROM {{ ref('cleansed_hosts') }}
  {% if is_incremental() %}
    WHERE CREATED_AT > (
      (SELECT max(CREATED_AT) FROM {{ this }})
        - INTERVAL '0 DAY'
    )
  {% endif %}
)

select
sum(o.amount) as total_revenue,
c.*
from
orders o
join cleansed_hosts c on o.customer_id = c.id
--</DBT_CODE>
--<ORIGINAL_CODE>
--select
--  sum(o.amount) as total_revenue,
--  c.*
--from
--  orders o
--  join cleansed_hosts c on o.customer_id = c.id
--</ORIGINAL_CODE>