-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-06-01T08:57:53.142Z
--<DBT_CODE>

    {{
      config(
        post_hook=["\n  \n  {% if target.name == 'prod' %}\n    {{log('Running retention policy for {{this}}. Staging retention days: N/A, Production retention days: 180.')}}\n    DELETE FROM {{this}} WHERE CREATED_AT < DATEADD(day, -180, CURRENT_DATE())\n  \n  {% endif %}\n  "],
      )
    }}
    
WITH orders AS (SELECT * FROM {{ ref('orders') }})
, 
cleansed_hosts AS (
  SELECT * FROM {{ ref('cleansed_hosts') }}
  {% if is_incremental() %}
    WHERE CREATED_AT > (
      (SELECT max(CREATED_AT) FROM {{ this }})
        - INTERVAL '0 DAY'
    )
  {% endif %}
)

select
c.*,  (select sum(o.amount) as total_revenue
from orders o
where o.customer_id = c.id) as total_revenue
from
cleansed_hosts c
--</DBT_CODE>
--<ORIGINAL_CODE>
--select
--  c.*,  (select sum(o.amount) as total_revenue
--   from orders o
--   where o.customer_id = c.id) as total_revenue
--from
--  cleansed_hosts c
--</ORIGINAL_CODE>