--- AUTO GENERATED BY MONTARA ---
--<DBT_CODE>

WITH RAW_HOSTS__RAW_HOSTS AS ( SELECT * FROM {{ source('RAW_HOSTS', 'RAW_HOSTS') }})

SELECT
id,
name,
is_superhost,
LEAST(DATEADD(year, 3, created_at), CURRENT_DATE) AS created_at,
LEAST(DATEADD(year, 3, updated_at), CURRENT_DATE) AS updated_at
FROM
raw_hosts__raw_hosts
ORDER BY
updated_at desc
--</DBT_CODE>
--<ORIGINAL_CODE>
--SELECT
--  id,
--  name,
--  is_superhost,
--  LEAST(DATEADD(year, 3, created_at), CURRENT_DATE) AS created_at,
--  LEAST(DATEADD(year, 3, updated_at), CURRENT_DATE) AS updated_at
--FROM
--  raw_hosts__raw_hosts
--ORDER BY
--  updated_at desc
--</ORIGINAL_CODE>