--- AUTO GENERATED BY MONTARA ---
--<DBT_CODE>
WITH RAW_HOSTS__RAW_HOSTS AS ( SELECT * FROM {{ source('RAW_HOSTS', 'RAW_HOSTS') }})

select
id,
name,
is_superhost,
MIN(DATEADD(year, 5, created_at),current_date) created_at,
MIN(DATEADD(year, 5, updated_at),current_date) updated_at
from
raw_hosts__raw_hosts
order by updated_at DESC
--</DBT_CODE>
--<ORIGINAL_CODE>
--select
--  id,
--  name,
--  is_superhost,
--  MIN(DATEADD(year, 5, created_at),current_date) created_at,
--  MIN(DATEADD(year, 5, updated_at),current_date) updated_at
--from
--  raw_hosts__raw_hosts
--order by updated_at DESC
--</ORIGINAL_CODE>