-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-08-11T10:18:15.879Z
--<DBT_CODE>

    {{
      config(
        post_hook=["\n  \n  {% if target.name == 'prod' %}\n    {{log('Running retention policy for {{this}}. Staging retention days: N/A, Production retention days: 180.')}}\n    DELETE FROM {{this}} WHERE CREATED_AT < DATEADD(day, -180, CURRENT_DATE())\n  \n  {% endif %}\n  "],
      )
    }}
    
WITH 
cleansed_hosts AS (
  SELECT * FROM {{ ref('cleansed_hosts') }}
  {% if is_incremental() %}
    WHERE CREATED_AT > (
      (SELECT max(CREATED_AT) FROM {{ this }})
        - INTERVAL '0 DAY'
    )
  {% endif %}
)
, stg_orders AS (SELECT * FROM {{ ref('stg_orders') }})

select
c.*,
(
select
max(o.order_id) as max_revenue
from
stg_orders o
where
o.customer_id = c.id
) as max_revenue
from
cleansed_hosts c

limit 10000
--</DBT_CODE>
--<ORIGINAL_CODE>
--select
--  c.*,
--  (
--    select
--      max(o.order_id) as max_revenue
--    from
--      stg_orders o
--    where
--      o.customer_id = c.id
--  ) as max_revenue
--from
--  cleansed_hosts c
--
--  limit 10000
--</ORIGINAL_CODE>