-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-05-29T12:25:46.787Z
--<DBT_CODE>

WITH 
cleansed_hosts AS (
  SELECT * FROM {{ ref('cleansed_hosts') }}
  {% if is_incremental() %}
    WHERE CREATED_AT > (
      (SELECT max(CREATED_AT) FROM {{ this }})
        - INTERVAL '0 DAY'
    )
  {% endif %}
)

select
*
from
cleansed_hosts
--</DBT_CODE>
--<ORIGINAL_CODE>
--select
--  *
--from
--  cleansed_hosts
--</ORIGINAL_CODE>