
# AUTO GENERATED BY MONTARA
#<ORIGINAL_CODE>
'''
List sources and models in the function definition as below
def test(sourceA, modelA)  
'''
def test(test_model):
  return model
#</ORIGINAL_CODE>
def model(dbt, session):
    test_model = dbt.ref('test_model')
    result = test(test_model)
    
    return result
