-- AUTO GENERATED BY MONTARA
--<DBT_CODE>

WITH cleansed_hosts AS (SELECT * FROM {{ ref('cleansed_hosts') }})

select * from cleansed_hosts
--</DBT_CODE>
--<ORIGINAL_CODE>
--select * from cleansed_hosts
----New stuff
--</ORIGINAL_CODE>