-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-05-29T12:43:44.282Z
--<DBT_CODE>

WITH cleansed_hosts AS (SELECT * FROM {{ ref('cleansed_hosts') }})

select * from cleansed_hosts
--</DBT_CODE>
--<ORIGINAL_CODE>
--select * from cleansed_hosts 
--</ORIGINAL_CODE>