-- AUTO GENERATED BY MONTARA
--<DBT_CODE>

WITH RAW_REVIEWS AS ( SELECT * FROM {{ source('RAW_REVIEWS', 'RAW_REVIEWS') }})

select * from raw_reviews
--</DBT_CODE>
--<ORIGINAL_CODE>
--select * from raw_reviews 
--</ORIGINAL_CODE>