name: Montara CI
on:
  pull_request:
    branches:
      - "main"
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  montara:
    runs-on: ubuntu-latest
    steps:
      - name: Montara CI
        uses: montara-io/montara-ci@v0.1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          webhookUrl: https://hooks.montara.io/pipeline/v2/trigger/791e57fc-5830-452d-bca2-1e1384a41168
