version: 2

sources:
  - name: RAW_HOSTS
    schema: RAW
    database: airbnb
    tables:
      - name: RAW_HOSTS
  - name: RAW_LISTINGS
    schema: RAW
    database: airbnb
    tables:
      - name: RAW_LISTINGS
        