-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-08-24T13:07:22.654Z
--<DBT_CODE>

WITH cleansed_hosts AS (SELECT * FROM {{ ref('cleansed_hosts') }})

select * from cleansed_hosts
--</DBT_CODE>
--<ORIGINAL_CODE>
--select * from cleansed_hosts
--</ORIGINAL_CODE>